[project]
name = "hpm-agent"
version = "0.1.0"
dependencies = [
    "torch",
    "pyro-ppl",
    "networkx",
    "python-levenshtein",
    "scikit-learn",
    "pydantic",
    "ray[default]",
    "numpy",
    "scikit-image>=0.26.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["hpm_ai_v3"]
