"""HPM AI v1: Recursive Self-Refactoring Engine.

Entry point for the polyglot self-improving loop.
"""
import os
import argparse
import numpy as np

from hpm.substrate.math import MathSubstrate
from hpm.substrate.wikipedia import WikipediaSubstrate
from hpm.substrate.pypi import PyPISubstrate
from hpm_ai_v1.substrates.code_substrate import LocalCodeSubstrate

from hpm_ai_v1.core.mutator import CodeMutationActor
from hpm_ai_v1.sandbox.executor import SandboxExecutor
from hpm_ai_v1.core.l5_compiler import L5Compiler
from hpm_ai_v1.store.concurrent_sqlite import ConcurrentSQLiteStore
from hpm_ai_v1.transpiler.encoders import ASTL2Encoder

# Underlying HPM Multi-Agent Framework
from hpm.agents.agent import Agent
from hpm.agents.multi_agent import MultiAgentOrchestrator
from hpm.config import AgentConfig
from hpm.field.field import PatternField

def main():
    parser = argparse.ArgumentParser(description="HPM AI v1 Recursive Engine")
    parser.add_argument("--repo_path", type=str, default=".", help="Path to codebase")
    parser.add_argument("--target_file", type=str, required=True, help="File to mutate")
    parser.add_argument("--db_path", type=str, default="hpm_ai_v1.db", help="Path to pattern store")
    args = parser.parse_args()

    print("Initializing HPM AI v1...")
    
    # 1. Initialize Substrates & Persistent Store
    # Leveraging core HPM substrates (Math, Wiki, PyPI) + Extension (Code)
    store = ConcurrentSQLiteStore(args.db_path)
    math_sub = MathSubstrate()
    code_sub = LocalCodeSubstrate(args.repo_path)
    wiki_sub = WikipediaSubstrate()
    pypi_sub = PyPISubstrate()
    
    # 2. Setup Multi-Agent Ensemble
    # We create an ensemble of 3 agents to 'mine' the codebase and external substrates.
    field = PatternField()
    
    agents = [
        Agent(AgentConfig(agent_id=f"agent_{i}", feature_dim=16), store=store, field=field)
        for i in range(3)
    ]
    orchestrator = MultiAgentOrchestrator(agents, field)
    
    print(f"Ensemble size: {len(agents)} agents sharing a concurrent PatternField.")
    
    # 3. Read Codebase & Mine Priors (using real HPM MathSubstrate)
    # The L3 'Laws' are fetched from external knowledge
    pareto_sim = math_sub.fetch("pareto")
    print(f"Mined {len(pareto_sim)} Relational Priors for 'pareto'")
    
    target_path = os.path.join(args.repo_path, args.target_file)
    original_code = code_sub.read_file(target_path)
    if not original_code:
        print(f"Failed to read {target_path}")
        return

    # 4. Setup Transpiler & Sandbox
    mutator = CodeMutationActor(l2_dim=16, l3_dim=32)
    sandbox = SandboxExecutor(args.repo_path)
    l2_enc = ASTL2Encoder()
    
    # 5. Baseline Evaluation
    print("Running baseline sandbox evaluation...")
    baseline_result = sandbox.evaluate_patch("") 
    if not baseline_result["success"]:
        print("Baseline tests failed! Fix the codebase before enabling self-refactoring.")
        return
        
    print(f"Baseline Cost: {baseline_result['cost_time']:.4f}s")
    
    # L5 Compiler initialized with real L5MetaMonitor features
    l5 = L5Compiler(baseline_cost=baseline_result['cost_time'])

    # 6. The Autonomous Refactoring Loop
    print("\nStarting Autonomous Refactoring Loop...")
    
    # Parse target into AST and encode its anatomy (L2)
    tree = code_sub.parse_ast(target_path)
    if not tree: return
    functions = code_sub.extract_functions(tree)
    if not functions:
        print("No functions found to mutate.")
        return
        
    l2_input = l2_enc.encode(functions[0])
    
    # Propose mutation via CodeMutationActor (which uses its internal L4 Head)
    patch = mutator.propose_mutation(original_code, args.target_file, l2_input)
    
    if not patch:
        print("No valid mutations generated by L4 Head.")
        return
        
    print("Mutation proposed. Running in Sandbox...")
    result = sandbox.evaluate_patch(patch)
    
    # 7. Metacognitive Gating
    accepted = l5.evaluate_mutation(result, patch)
    
    if accepted:
        print("Mutation Accepted. Applying to live codebase...")
        l5.commit_succession(patch, args.repo_path)
    else:
        print("Mutation Rejected. Maintaining current generation.")

if __name__ == "__main__":
    main()
