from typing import Protocol, runtime_checkable
import numpy as np


@runtime_checkable
class Pattern(Protocol):
    id: str
    level: int

    def log_prob(self, x: np.ndarray) -> float: ...
    def description_length(self) -> float: ...
    def connectivity(self) -> float: ...
    def compress(self) -> float: ...
    def update(self, x: np.ndarray) -> 'Pattern': ...
    def recombine(self, other: 'Pattern') -> 'Pattern': ...
    def is_structurally_valid(self) -> bool: ...
    def to_dict(self) -> dict: ...

    @classmethod
    def from_dict(cls, d: dict) -> 'Pattern': ...
