from typing import Protocol
import numpy as np


class PatternStore(Protocol):
    def save(self, pattern, weight: float, agent_id: str) -> None: ...
    def load(self, pattern_id: str, agent_id: str) -> tuple: ...
    def query(self, agent_id: str) -> list: ...
    def query_all(self) -> list: ...
    def delete(self, pattern_id: str, agent_id: str) -> None: ...
    def update_weight(self, pattern_id: str, agent_id: str, weight: float) -> None: ...
