from typing import Protocol
import numpy as np


class Domain(Protocol):
    def observe(self) -> np.ndarray: ...
    def feature_dim(self) -> int: ...
    def deep_perturb(self) -> 'Domain': ...
    def surface_perturb(self) -> 'Domain': ...
    def transfer_probe(self, near: bool) -> list[tuple[np.ndarray, int]]: ...
